### ISSUE TITLE
Can you run this on all existing subtitles?

### ISSUE THREAD

**Issue by fillilutten** [TheCaptain989/bazarr-cleansubs#2]
Can you somehow run this on all existing subtitles?

**Comment by TheCaptain989** [comment]
(Sorry for the delayed reply @fillilutten)

Yes, you can absolutely do this from a Linux command-line.  Note that the log output (to the screen) will be messy and hard to read, but it will clean the subtitle files the same way.

As an example, you could run this one-liner shell script:
`find "/path/to files/" -name *.srt -exec /config/cleansubs.sh "{}" \;`

**Comment by fillilutten** [comment]
> (Sorry for the delayed reply @fillilutten)
> 
> Yes, you can absolutely do this from a Linux command-line. Note that the log output (to the screen) will be messy and hard to read, but it will clean the subtitle files the same way.
> 
> As an example, you could run this one-liner shell script:
> `find "/path/to files/" -name *.srt -exec /config/cleansubs.sh "{}" \;`

Sorry for noob question, but '/path/to files/' would that be the path to my movies folder? Like 'srv/disk/media/movies' ? 

Edit: Yes! Got it to work, thanks! :D

**Comment by TheCaptain989** [comment]
Great.

**Comment by MiranoVerhoef** [comment]
Heyy, Sorry for opening this ticket again, but running that script inside my Bazarr docker makes it loop the same items over and over again, when doing it from my macbook or unraid CLI it does work.

Is there a way for me to donate a little for you making this script? it works like heaven

**Comment by MiranoVerhoef** [comment]
The mention above is just a heads-up for people that might run into this, i testen it with 1 season folder and found it out!

**Comment by TheCaptain989** [comment]
Let me make sure I understand.  You're putting this in Bazarr:

`/config/cleansubs.sh "{{subtitles}}" ;`

And it's looping?

P.S. - Thanks for the offer, but I'm not currently accepting any money.

**Comment by MiranoVerhoef** [comment]
Let me elaborate:

I've had this running perfectly and still is whenever i add a new subtitles to bazarr!


I've read the original reddit post that stated:

# Run this script across your whole media library:
find /path/to/library -name '*.srt' -exec /path/to/sub-clean.sh "{}" \;

When applying the above using the console of my bazarr docker, it keeps looping. i did that when i just found out your script but didnt notice. (i can recreate this)

Then i mounted my plex folder to my macbook and used the same command and it did just check each .srt once instead of looping.

--------

Thank you for the work you've spend on making this! :)

**Comment by TheCaptain989** [comment]
Huh. I didn't know there were posts on Reddit about my script. I would be interested to know why it looped.

Anyway, you're welcome!

**Comment by hugalafutro** [comment]
Hi, sorry for barging in, but I'm not having any luck with this, any help appreciated.

`find "/mnt/pool1/media_vault/media2/movies2/" -name *.srt -exec /mnt/apps/scripts/cleansubs.sh "{}" \;`
```
/mnt/apps/scripts/cleansubs.sh: eval: line 107: syntax error near unexpected token `('
/mnt/apps/scripts/cleansubs.sh: eval: line 107: `set --  /mnt/pool1/media_vault/media2/movies2/Nobody (2021)/Nobody (2021) Bluray-1080p x265.srt'
/mnt/apps/scripts/cleansubs.sh: line 127: /config/log/cleansubs.log: No such file or directory
stat: cannot statx '/config/log/cleansubs.log': No such file or directory
/mnt/apps/scripts/cleansubs.sh: line 129: [: -gt: unary operator expected
Error|No subtitle file specified! Not called from Bazarr?

cleansubs.sh   Version: 1.0
Subtitle processing script designed for use with Bazarr

Source: https://github.com/TheCaptain989/bazarr-cleansubs

Usage:
  /mnt/apps/scripts/cleansubs.sh {-f|--file} <subtitle_file> [{-d|--debug} [<level>]]

Options and Arguments:
  -f, --file <subtitle_file>       subtitle file in SRT format
  -d, --debug [<level>]            enable debug logging
                                   Level is optional, default of 1 (low)
      --help                       display this help and exit
      --version                    display script version and exit

Example:
  cleansubs.sh -f "/video/The Muppet Show 02x13 - Zero Mostel.en.srt"  # When used standalone on the command line
  cleansubs.sh "{{subtitles}}" ;                                       # As used in Bazarr
```
and then it just loops like that for each movie

**Comment by hugalafutro** [comment]
I modified the line (was throwing errors without `-f`) and made it do a line break after each entry for ease of reading the output:
`find /media2/movies2/ -name *.srt -exec bash -c "/config/cleansubs.sh -f \"{}\";printf \"\\n\"" \;`

**Comment by TheCaptain989** [comment]
Ah.  Yes, I made a change to the script for version 1.0 and added the `-f` command-line argument, but it should not be required.

Congratulations, you just found a bug!  😜

I've opened a new Issue #4 for it.  Thanks!

**Comment by TheCaptain989** [comment]
BTW, the lack of line-break on stdout was intentional because of the way Bazarr logs work.  I'll see if I can't figure out a better way to handle that.

**Comment by hugalafutro** [comment]
Always happy to find a bug 😄 

I stumbled upon this script when I started moving all my -arrs to TrueNAS apps. Integrating it in bazarr was easy, but I had trouble running it on the host as I wanted to process existing media and run it via cron as many media is already imported with subs and bazarr only looks for missing (same why I seeked to add the line break as I'd see more logs from outside processing than in bazarr).

Trying to run it from container I struggled a bit as the app runs as a docker container in kubernetes pod on truenas so the name changes all the time but finally I got it running like this:
```
POD=$(k3s kubectl -n ix-bazarr get pods --no-headers | grep -E -v "(redis|postgresql|svclb)" | awk '{print $1}')
k3s kubectl -n ix-bazarr exec -it ${POD} -- find /media/ -name *.srt -exec bash -c "/config/cleansubs.sh -f \"{}\";printf \"\\n\"" \;
k3s kubectl -n ix-bazarr exec -it ${POD} -- find /media2/ -name *.srt -exec bash -c "/config/cleansubs.sh -f \"{}\";printf \"\\n\"" \;
```
At the end, out of literal thousands of files it failed only on few with `$` in name so overall great success!

Very happy with your script as it even cleaned subs I previously considered cleaned by the script I used before.

**Comment by TheCaptain989** [comment]
Well, I'm glad you're happy with it.
I think I fixed the dollar-sign issue with this latest version, so if you get a chance, you could maybe run it on those last few files.

**Comment by hugalafutro** [comment]
edit: nvm figured it out: changed line 155 to /config/log/cleansubs.log, although I do not call the script by bazarr, I still call it within bazarr which can only write to /app and /config afaik. will report with any further errors once it crawls thru my library

getting these errors with 1.01 even when running the script with no arguments
```
/config/cleansubs.sh: line 130: ./cleansubs.log: Read-only file system
stat: can't stat './cleansubs.log': No such file or directory
/config/cleansubs.sh: line 132: [: -gt: unary operator expected
```

can't figure out why it's trying to look for the log in `./` instead of `/config/log`

**Comment by hugalafutro** [comment]
Processed files with dollar sign ok. got error on 2 files, but when I look into the location there is no `.tmp` files and the subtitles look/play ok. Other errors are maybe from malformatted subs? All in all it processed 99%+ of the subs ok which is great!

I don't want to bother you with fixing 2 files out of thousands, but in case you're interested about the errors:
```
awk: cmd. line:66: Invalid format specifier
Error|Script failed. Unable to locate or invalid file: /media/tv/Black Mirror/Season 01/S01E03 - The Entire History of You WEBRip-1080p.en.srt.tmp
awk: cmd. line:73: Invalid format specifier
awk: cmd. line:73: Invalid format specifier
awk: cmd. line:73: Invalid format specifier
awk: cmd. line:73: Invalid format specifier
awk: cmd. line:73: Invalid format specifier
awk: cmd. line:73: Invalid format specifier
awk: cmd. line:73: Invalid format specifier
awk: cmd. line:73: Invalid format specifier
Error|Script failed. Unable to locate or invalid file: /media2/tv2/Salad Fingers/Specials/S00E03 - Market SDTV.srt.tmp
```

**Comment by TheCaptain989** [comment]
> can't figure out why it's trying to look for the log in `./` instead of `/config/log`

I saw your edit too, but I'm going to change this logic anyway.  It wasn't well thought out when I added the ./ log output.

**Comment by TheCaptain989** [comment]
FYI, I've just commited a new Develop branch that fixes the log issue.  I've performed limited testing.

**Comment by TheCaptain989** [comment]
First, thank you for the vote of confidence.

> Processed files with dollar sign ok. got error on 2 files, but when I look into the location there is no `.tmp` files and the subtitles look/play ok. Other errors are maybe from malformatted subs? All in all it processed 99%+ of the subs ok which is great!
> 
> I don't want to bother you with fixing 2 files out of thousands, but in case you're interested about the errors:
> 
> ```
> awk: cmd. line:66: Invalid format specifier
> Error|Script failed. Unable to locate or invalid file: /media/tv/Black Mirror/Season 01/S01E03 - The Entire History of You WEBRip-1080p.en.srt.tmp
> awk: cmd. line:73: Invalid format specifier
> awk: cmd. line:73: Invalid format specifier
> awk: cmd. line:73: Invalid format specifier
> awk: cmd. line:73: Invalid format specifier
> awk: cmd. line:73: Invalid format specifier
> awk: cmd. line:73: Invalid format specifier
> awk: cmd. line:73: Invalid format specifier
> awk: cmd. line:73: Invalid format specifier
> Error|Script failed. Unable to locate or invalid file: /media2/tv2/Salad Fingers/Specials/S00E03 - Market SDTV.srt.tmp
> ```

From these logs, I think that the `printf` function is failing, which is weird.  I'll try to dive a little deeper as to why, but it maybe be a malformed subtitle file.  If you're willing to share your two .srt files, that would be awesome.

**Comment by TheCaptain989** [comment]
Doh!  Another bug.  Man, you're good. 🤣 

Please try the latest version.

**Comment by hugalafutro** [comment]
With 1.02 all errors apart from the 2 particular subtitles are gone. Thanks for the fixes!
```
Error|Script failed. Unable to locate or invalid output file: /media/tv/Black Mirror/Season 01/S01E03 - The Entire History of You WEBRip-1080p.en.srt.tmp
Error|Script failed. Unable to locate or invalid output file: /media2/tv2/Salad Fingers/Specials/S00E03 - Market SDTV.srt.tmp
```

proof the `.tmp` files are not there:
```
ls: /media/tv/Black Mirror/Season 01/*.tmp: No such file or directory
ls: /media2/tv2/Salad Fingers/Specials/*.tmp: No such file or directory
```

The subtitle files zipped, uploaded to my nextcloud: https://o.o5.ddns.net/meow

**Comment by TheCaptain989** [comment]
> The subtitle files zipped, uploaded to my nextcloud: https://o.o5.ddns.net/meow

Thank you!  This was incredibly helpful.  I fixed a regex issue and now the script completes with no errors on these two files.  I've uploaded version 1.02a with the fix.

**Comment by hugalafutro** [comment]
Brilliant thanks again! Out of curiosity was it the content of the subs that was problematic or their name? Just thinking how rare the occurrence must be if it was just 2 files out of around 10k

**Comment by TheCaptain989** [comment]
It was the content, not the name.  Specifically, these files used a dot [.] instead of a comma [,] in the timestamps to separate the seconds from milliseconds.  I thought only the comma was allowed, but other subtitle tools opened your two files without complaining, so I just added both to my regex.
