### ISSUE TITLE
Dollar sign in filename breaks processing

### ISSUE THREAD

**Issue by hugalafutro** [TheCaptain989/bazarr-cleansubs#3]
filename: `S04E05 - The $2,000,000 Defense SDTV.avi`

```
Error|Input file not found: "/media/tv/Alfred Hitchcock Presents (1955)/Season 04/S04E05 - The ,000,000 Defense SDTV.en.srt"
```

thanks for your tool, had a bit of trouble getting it work on baremetal nas, but it works perfectly from inside bazarr container

**Comment by TheCaptain989** [comment]
Thanks for reporting this.  Experimentally, if you use the `--file` option it appears to work correctly.

P.S. - This is related to the other bug #4.
